"""Generate SVG screenshots of Gemi's UI for the README.

Uses rich.Console(record=True).export_svg() to capture real terminal output
as standalone, GitHub-renderable SVGs. Produces:
  assets/banner.svg            startup banner with agent info
  assets/picker.svg            agent picker UI
  assets/status.svg            fleet status table
  assets/help.svg              /help output
  assets/tool-result.svg       a sample tool call + result
  assets/streaming.svg         streaming response example
  assets/yolo-warning.svg      YOLO activation warning
"""
from __future__ import annotations
import sys
from pathlib import Path

ASSETS = Path(__file__).parent / "assets"
ASSETS.mkdir(exist_ok=True)
sys.path.insert(0, str(Path(__file__).parent))

from rich.console import Console
from rich.text import Text
from rich.panel import Panel
from rich.syntax import Syntax
from rich.table import Table
from rich.box import ROUNDED


def make_console(width: int = 100, height: int = 30) -> Console:
    """Recording console — output goes to memory, not stdout."""
    return Console(record=True, width=width, color_system="truecolor",
                   force_terminal=True, file=open(__file__, "rb"))  # placeholder


def fresh_console(width: int = 100, theme=None) -> Console:
    """A recording console that doesn't write to stdout."""
    import io
    return Console(record=True, width=width, color_system="truecolor",
                   force_terminal=True, file=io.StringIO(), theme=theme)


def save(c: Console, name: str, title: str = "Gemi") -> None:
    out = ASSETS / name
    svg = c.export_svg(title=title, code_format="""<svg class="rich-terminal" viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg">
    <!-- Generated by Rich for Gemi (https://github.com/space-kitty-o/gemi) -->
    <style>
        @import url("https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap");
        .{unique_id}-matrix {{
            font-family: JetBrains Mono, Cascadia Code, Consolas, monospace;
            font-size: {char_height}px;
            line-height: {line_height}px;
            font-variant-east-asian: full-width;
        }}
        .{unique_id}-title {{
            font-size: 18px;
            font-weight: bold;
            font-family: JetBrains Mono, sans-serif;
        }}
        {styles}
    </style>
    <defs>
        <clipPath id="{unique_id}-clip-terminal">
            <rect x="0" y="0" width="{terminal_width}" height="{terminal_height}" />
        </clipPath>
        {lines}
    </defs>
    {chrome}
    <g transform="translate({terminal_x}, {terminal_y})" clip-path="url(#{unique_id}-clip-terminal)">
    {backgrounds}
    <g class="{unique_id}-matrix">
    {matrix}
    </g>
    </g>
</svg>""")
    out.write_text(svg, encoding="utf-8")
    print(f"  wrote {out.name}  ({len(svg):,} bytes)")


# ---------- 1. Banner --------------------------------------------------

def gen_banner():
    from gemi.ui.banner import print_banner
    from gemi.ui.theme import get_rich_theme
    from gemi.config import AgentDef

    fake_agent = AgentDef(
        slug="local-agent-2",
        name="Local Agent 2",
        directory="agent-2",
        port=8002, proxy_port=9002,
        role="precision coder",
        model="Qwen3.6-35B-A3B-Q8_K_P",
        quant="Q8_K_P",
        context=8192, parallel=1, can_think=True,
        quality_tier="premium",
    )
    import io
    c = Console(record=True, width=92, color_system="truecolor",
                force_terminal=True, file=io.StringIO(),
                theme=get_rich_theme("dark"))
    print_banner(c, fake_agent, version="0.1.0", workspace=Path("/home/you/myproject"))
    save(c, "banner.svg", title="gemi -- launch")


# ---------- 2. Status table --------------------------------------------

def gen_status():
    from gemi.ui.theme import get_rich_theme
    c = fresh_console(width=110, theme=get_rich_theme("dark"))

    t = Table(border_style="bright_magenta", title="\n  ✻ Agent Fleet  v0.1.0", title_justify="left",
              show_lines=False, box=ROUNDED, padding=(0, 1))
    t.add_column("#", style="dim", justify="right", width=3)
    t.add_column("Slug", style="bold cyan")
    t.add_column("Role", style="dim")
    t.add_column("Quant", style="bold yellow")
    t.add_column("Ctx", style="dim", justify="right")
    t.add_column("P", style="dim", justify="right")
    t.add_column("Tier", style="dim")
    t.add_column("Status", justify="center")

    fleet = [
        ("1", "local-agent-1", "general coder",     "Q4_K_M", "16,384", "2", "high",     ("● READY", "bold green")),
        ("2", "local-agent-2", "precision coder",   "Q8_K_P", "8,192",  "1", "premium",  ("● READY", "bold green")),
        ("3", "local-agent-3", "fast throughput",   "IQ3_M",  "32,768", "4", "fast",     ("○ OFF",   "dim red")),
        ("4", "local-agent-4", "ultra-cheap",       "Q2_K_P", "32,768", "4", "economy",  ("○ OFF",   "dim red")),
        ("5", "local-agent-5", "balanced coder",    "Q6_K_M", "12,288", "1", "high",     ("◐ MODEL", "bold yellow")),
    ]
    for row in fleet:
        s = Text(row[7][0], style=row[7][1])
        t.add_row(row[0], row[1], row[2], row[3], row[4], row[5], row[6], s)
    c.print(t)
    save(c, "status.svg", title="gemi -- fleet status")


# ---------- 3. Picker --------------------------------------------------

def gen_picker():
    from gemi.ui.theme import get_palette, get_rich_theme

    c = fresh_console(width=104, theme=get_rich_theme("dark"))
    p = get_palette("dark")

    c.print()
    c.print(f"  [bold {p.buddy}]✻ Agents & Modes[/]")
    c.print()

    fleet = [
        ("1", "Mini Max Gemi",        "high",    "Q4_K_M",  "24K", "p4", "lead orchestrator"),
        ("2", "Local Agent 2",        "standard","Q5_K_M",  "16K", "p2", "GLM reviewer"),
        ("3", "Local Agent 3",     "active high","Q4_K_M",  "16K", "p2", "general coder",      True),
        ("4", "Local Agent 4",        "fast",    "IQ3_M",   "32K", "p4", "fast throughput"),
        ("5", "Local Agent 5",        "premium", "Q8_K_P",  "8K",  "p1", "precision coder"),
        ("6", "Local Agent 6",        "economy", "Q2_K_P",  "32K", "p4", "ultra-cheap"),
        ("7", "Local Agent 7",        "fast",    "IQ3_M",   "32K", "p4", "parallel twin"),
        ("8", "Local Agent 8",        "high",    "Q6_K_M",  "12K", "p1", "Wasserstein 27B"),
        ("9", "Local Agent 9",        "premium", "Q8_0",    "8K",  "p1", "27B precision"),
        ("0", "Local Agent 10",       "standard","Q8_0",    "8K",  "p1", "image generation"),
    ]
    tier_glyph = {"premium": "◉", "high": "●", "standard": "●",
                  "fast": "◐", "economy": "○", "active high": "●"}

    for row in fleet:
        idx, name, tier, quant, ctx, par, role = row[:7]
        active = len(row) == 8 and row[7]
        running = idx in ("1", "3", "5")  # mocked
        marker = f"[bold {p.success}]●[/]" if running else f"[dim]○[/]"
        check = f"[bold {p.success}]✓[/]" if active else " "
        glyph = tier_glyph.get(tier, "·")
        name_style = f"bold {p.info}" if active else "muted"
        c.print(f"   [bold {p.buddy_shimmer}]{idx}[/]  {marker}  "
                f"[{name_style}]{name:<22}[/]  {check}  "
                f"[{p.warning}]{glyph}[/] [muted]{tier:<13}[/]"
                f"[bold {p.warning}]{quant:<7}[/] [dim]ctx {ctx:<5} {par:<4}[/]"
                f"[muted]{role}[/]")

    c.print()
    c.print(f"   [bold {p.buddy_shimmer}]y[/] [muted]YOLO     [/]"
            f"[bold {p.buddy_shimmer}]p[/] [muted]PLAN     [/]"
            f"[bold {p.buddy_shimmer}]a[/] [muted]AUTO     [/]"
            f"[bold {p.buddy_shimmer}]Esc[/] [muted]cancel[/]")
    c.print()
    c.print(f"   [muted]press [bold {p.buddy_shimmer}]1-9[/]"
            f"[muted] for agent · [/][bold {p.buddy_shimmer}]y/p/a[/]"
            f"[muted] for modes[/]")

    save(c, "picker.svg", title="gemi -- agent picker (Ctrl+M)")


# ---------- 4. /help ---------------------------------------------------

def gen_help():
    from gemi.ui.theme import get_palette, get_rich_theme
    c = fresh_console(width=104, theme=get_rich_theme("dark"))
    p = get_palette("dark")

    c.print()
    c.print(f"  [bold {p.buddy}]✻ Gemi commands[/]  [muted](70 commands, 38 aliases)[/]")

    cats = [
        ("◇  Session",
         [("/clear", "Clear conversation history", "/c"),
          ("/save", "Save current session", "/s"),
          ("/resume", "Resume a saved session", "/r"),
          ("/rewind", "Rewind to a specific turn", "/rw"),
          ("/timeline", "Show conversation timeline", "/tl")],
         p.info),
        ("◈  Modes",
         [("/yolo", "Toggle YOLO (bypass permissions)", ""),
          ("/plan", "Toggle plan-before-act mode", ""),
          ("/autopilot", "Toggle non-stop autonomous mode", "/ap"),
          ("/approval", "Toggle interactive approval flow", "")],
         p.warning),
        ("✻  Fleet",
         [("/agent", "Open the agent picker", "/a"),
          ("/status", "Show fleet status table", ""),
          ("/vote", "Run prompt across all running agents", "/v"),
          ("/race", "First-to-finish wins", "/rc"),
          ("/task", "Spawn a sub-agent task", "/tk")],
         p.buddy),
        ("$  Shell",
         [("/sh", "Run a bash one-liner: /sh ls -la", ""),
          ("/ps", "Run a PowerShell command", ""),
          ("/cmd", "Run a Windows cmd.exe command", ""),
          ("/run", "Detect & run a project task", ""),
          ("!cmd", "Quick shell — `!ls -la` runs directly", "")],
         p.success),
    ]
    for title, rows, color in cats:
        c.print()
        c.print(f"   [bold {color}]{title}[/]")
        for cmd, desc, alias in rows:
            alias_str = f"  [dim]({alias})[/]" if alias else ""
            c.print(f"      [bold {p.buddy_shimmer}]{cmd:<14}[/]  [muted]{desc}[/]{alias_str}")
    c.print()
    c.print(f"  [muted]tip: type [/][bold {p.buddy_shimmer}]{{[/]"
            f"[muted] for multi-line input  ·  [/][bold {p.buddy_shimmer}]/theme[/] "
            f"[muted]to change colors  ·  [/][bold {p.buddy_shimmer}]Ctrl+M[/]"
            f"[muted] picks agent[/]")
    c.print()

    save(c, "help.svg", title="gemi -- /help")


# ---------- 5. Tool result rendering -----------------------------------

def gen_tool_result():
    from gemi.ui.theme import get_palette, get_rich_theme
    c = fresh_console(width=100, theme=get_rich_theme("dark"))
    p = get_palette("dark")

    c.print()
    c.print(f"  [bold {p.buddy_shimmer}]>[/] explain how the QueryEngine handles streaming")
    c.print()
    c.print(f"  ✻", style=f"bold {p.buddy_shimmer}")
    c.print()
    c.print(f"    Let me read the file to give you an accurate answer.")
    c.print()
    c.print(f"  [dim]⎯[/][bold {p.buddy}]◇[/][dim]⎯ [/]"
            f"[bold yellow]read_file[/]  [dim]gemi/query_engine.py[/]")
    c.print(f"  [dim]⎯[/][bold {p.success}]✓[/][dim]⎯ [/]"
            f"[bold yellow]read_file[/]  [dim]4.2KB, 156 lines · 0.04s[/]")

    code = """    def _stream_round(self, tools):
        payload = _build_payload(self.messages, ...)
        with self._client.stream("POST", "/v1/messages", json=payload) as resp:
            for line in resp.iter_lines():
                if line.startswith("data: "):
                    data = json.loads(line[6:])
                    if data.get("type") == "content_block_delta":
                        delta = data.get("delta", {})
                        if delta.get("type") == "text_delta":
                            chunk = delta.get("text", "")
                            self.on_text_chunk(chunk)
        return _collect_sse_to_response(events)"""
    syntax = Syntax(code, "python", theme="monokai", line_numbers=False, indent_guides=True)
    c.print(Panel(syntax, border_style=p.border, expand=False, padding=(0, 1)))

    c.print()
    c.print(f"    The streaming flow is straightforward:")
    c.print()
    c.print(f"    1. Open an `httpx.stream` POST to the proxy")
    c.print(f"    2. Iterate SSE events as they arrive")
    c.print(f"    3. For each `text_delta`, call `on_text_chunk` so the REPL")
    c.print(f"       renders incrementally")
    c.print(f"    4. After the stream ends, assemble all events into the")
    c.print(f"       complete response and check for tool_use blocks")
    c.print()
    c.print(f"  [muted]· 234 in / 91 out  ·  3.2s  ·  1 tool  ·  $0.0011[/]")
    c.print()

    save(c, "tool-result.svg", title="gemi -- streaming + tool call")


# ---------- 6. YOLO warning --------------------------------------------

def gen_yolo_warning():
    from gemi.ui.theme import get_palette, get_rich_theme
    c = fresh_console(width=92, theme=get_rich_theme("dark"))
    p = get_palette("dark")

    c.print()
    c.print(f"  [bold {p.yolo}]⚡ YOLO MODE ACTIVE[/]  "
            f"[muted]all permission gates bypassed, dangerous tools enabled[/]")
    c.print()
    c.print(f"  [bold {p.warning}]⚠  Authorized use only.[/]  "
            f"[muted]Offensive tools (exploits, recon, websec, api_test,[/]")
    c.print(f"  [muted]bash, cmd, powershell, hash_crack, payload_gen) are for:[/]")
    c.print(f"  [muted]  • systems you own or have written permission to test[/]")
    c.print(f"  [muted]  • bug-bounty programs within published scope[/]")
    c.print(f"  [muted]  • CTFs, educational labs, authorized red-team work[/]")
    c.print()
    c.print(f"  [muted]Unauthorized use violates the CFAA / Computer Misuse Act /[/]")
    c.print(f"  [muted]equivalent statutes in your jurisdiction. You alone bear[/]")
    c.print(f"  [muted]the legal and ethical responsibility for what you do.[/]")
    c.print()
    c.print(f"  [muted]See[/]  [bold {p.buddy_shimmer}]DISCLAIMER.md[/]  "
            f"[muted]for full terms.[/]")
    c.print()

    save(c, "yolo-warning.svg", title="gemi -- YOLO activation warning")


# ---------- 7. Free-API tools example ----------------------------------

def gen_free_apis():
    from gemi.ui.theme import get_palette, get_rich_theme
    c = fresh_console(width=92, theme=get_rich_theme("dark"))
    p = get_palette("dark")

    c.print()
    c.print(f"  [bold {p.buddy_shimmer}]>[/] what's the weather in Tokyo and BTC price")
    c.print()
    c.print(f"  ✻ [muted]calling weather + crypto_price in parallel...[/]",
            style=f"bold {p.buddy_shimmer}")
    c.print()
    c.print(f"  [dim]⎯[/][bold {p.success}]✓[/][dim]⎯ [/]"
            f"[bold yellow]weather[/]  [dim]Tokyo, Japan[/]  [dim]0.42s[/]")
    c.print(f"      [muted]│[/] # Weather — Tokyo, Japan")
    c.print(f"      [muted]│[/] Current: 18°C  humidity 64%  wind 12 km/h")
    c.print(f"      [muted]│[/] Forecast:")
    c.print(f"      [muted]│[/]   Tomorrow  lo 14°C / hi 21°C  rain 0.4mm")
    c.print(f"      [muted]│[/]   Day +2    lo 13°C / hi 19°C  rain 2.1mm")
    c.print()
    c.print(f"  [dim]⎯[/][bold {p.success}]✓[/][dim]⎯ [/]"
            f"[bold yellow]crypto_price[/]  [dim]bitcoin,ethereum[/]  [dim]0.31s[/]")
    c.print(f"      [muted]│[/] # Crypto prices")
    c.print(f"      [muted]│[/]   bitcoin    USD  $76,032.00  [bold red]▼1.40%[/]  mcap $1522.2B")
    c.print(f"      [muted]│[/]   ethereum   USD   $2,257.20  [bold red]▼3.02%[/]  mcap $272.4B")
    c.print()
    c.print(f"    Tokyo is a cool autumn day with light winds. Bitcoin is at")
    c.print(f"    $76K, down 1.4% in 24h, with Ethereum down a bit more at -3%.")
    c.print()
    c.print(f"  [muted]· 1.2K in / 248 out  ·  1.8s  ·  2 tools  ·  $0.0008[/]")
    c.print()

    save(c, "free-apis.svg", title="gemi -- free public APIs")


if __name__ == "__main__":
    gen_banner()
    gen_status()
    gen_picker()
    gen_help()
    gen_tool_result()
    gen_yolo_warning()
    gen_free_apis()
    print(f"\nDone. {len(list(ASSETS.glob('*.svg')))} SVGs in {ASSETS}")
